language: objective-c
xcode_workspace: PYAegis.xcworkspace
xcode_scheme: PYAegis

matrix:
  include:
     - xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
       osx_image: xcode10.1
       env: DESTINATION="platform=iOS Simulator,OS=12.1,name=iPhone X"
     - xcode_destination: platform=iOS Simulator,OS=11.1,name=iPhone X
       osx_image: xcode9.4
       env: DESTINATION="platform=iOS Simulator,OS=11.1,name=iPhone X"
     - xcode_destination: platform=iOS Simulator,OS=10.1,name=iPhone 7
       osx_image: xcode9.4
       env: DESTINATION="platform=iOS Simulator,OS=10.1,name=iPhone 7"
     - xcode_destination: platform=iOS Simulator,OS=9.3,name=iPhone 6
       osx_image: xcode9.4
       env: DESTINATION="platform=iOS Simulator,OS=9.3,name=iPhone 6"
     - xcode_destination: platform=iOS Simulator,OS=8.3,name=iPhone 6
       osx_image: xcode10.1
       env: DESTINATION="platform=iOS Simulator,OS=8.3,name=iPhone 6"

before_install:
  - npm install ios-sim -g
  - ios-sim start --devicetypeid "com.apple.CoreSimulator.SimDeviceType.iPhone-6, 8.3"

after_success: bash <(curl -s https://codecov.io/bash)
